//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinyCLR_F769
{
    
    internal partial class Resource1
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((Resource1.manager == null))
                {
                    Resource1.manager = new System.Resources.ResourceManager("TinyCLR_F769.Resource1", typeof(Resource1).Assembly);
                }
                return Resource1.manager;
            }
        }
        //internal static System.Drawing.Font GetFont(Resource1.FontResources id)
        //{
        //    return ((System.Drawing.Font)(ResourceManager.GetObject(((short)(id)))));
        //}
        [System.SerializableAttribute()]
        internal enum FontResources : short
        {
            small = 13070,
            NinaB = 18060,
        }
    }
}
